### ISSUE TITLE
Add `position` prop

### ISSUE THREAD

**Issue by kevva** [kevva/deku-tooltip#1]
Would be nice to be able to specify if the tooltip should be displayed on `top`, `right`, `bottom` or `left`.

**Comment by kevva** [comment]
@gillstrom, are you interested in this? Or even better, the whole module?

**Comment by kevva** [comment]
@gillstrom @alonalon, does anyone of you want this module? I'm not interested in maintaining it anymore.

**Comment by hafffe** [comment]
Sure :)

**Comment by kevva** [comment]
Done :).
